FROM postgres:18-alpine

# Install pg_cron from source
RUN apk add --no-cache git build-base postgresql-dev \
    && cd /tmp \
    && git clone https://github.com/citusdata/pg_cron.git \
    && cd pg_cron \
    && git checkout v1.6.0 \
    && make \
    && make install \
    && cd / \
    && rm -rf /tmp/pg_cron \
    && apk del git build-base postgresql-dev

# Enable pg_cron extension
RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/local/share/postgresql/postgresql.conf.sample
RUN echo "cron.database_name = 'galaxy_empire'" >> /usr/local/share/postgresql/postgresql.conf.sample

USER postgres